### ISSUE TITLE
Priser mangler £

### ISSUE THREAD

**Issue by bqardi** [kings-n-queen/hifi-corner#137]
Priser mangler pund tegnet (£) på single-page og category-page (både før-/efter- pris).
(Dette burde kunne klares udelukkende med CSS, men hardcoded HTML eller concatenation i JavaScript er også udmærkede løsninger.)
Et eksempel på en ren CSS løsning:

```CSS
.className::before {
    content: "£";
    margin-right: 3px;
}
```

**DoD:** Når pund tegnet (£) er vist foran prisen alle steder hvor der vises priser.
